# Generated by Django 5.2.6 on 2025-09-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nifty_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points', models.IntegerField(help_text='e.g. +100 or -100')),
                ('fii', models.DecimalField(decimal_places=2, help_text='FII activity', max_digits=15)),
                ('dii', models.DecimalField(decimal_places=2, help_text='DII activity', max_digits=15)),
                ('pcr', models.DecimalField(decimal_places=2, help_text='Put/Call Ratio', max_digits=5)),
                ('global_markets', models.CharField(help_text='e.g. US up, Asia down', max_length=255)),
                ('decision', models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish')], max_length=10)),
                ('important_news', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
