# Generated by Django 5.2.6 on 2025-09-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketrecord',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='decision',
            field=models.CharField(blank=True, choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='dii',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='fii',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='global_markets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='pcr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='points',
            field=models.DecimalField(decimal_places=2, help_text='Change from prev close', max_digits=10),
        ),
        migrations.CreateModel(
            name='HourlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('nifty_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fii', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dii', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pcr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('market_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly', to='marketdata.marketrecord')),
            ],
        ),
    ]
