# Generated by Django 5.2.6 on 2025-09-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_alter_marketrecord_date_alter_marketrecord_decision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketrecord',
            options={'ordering': ['-date', 'hour']},
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='hour',
            field=models.TimeField(blank=True, help_text='Null = daily, set = hourly snapshot', null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='decision',
            field=models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish')], default='Bullish', max_length=10),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='dii',
            field=models.DecimalField(decimal_places=2, default=0, help_text='DII activity', max_digits=15),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='fii',
            field=models.DecimalField(decimal_places=2, default=0, help_text='FII activity', max_digits=15),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='global_markets',
            field=models.CharField(blank=True, help_text='e.g. US up, Asia down', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='pcr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Put/Call Ratio', max_digits=5),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='points',
            field=models.IntegerField(default=0, help_text='e.g. +100 or -100'),
        ),
        migrations.AlterUniqueTogether(
            name='marketrecord',
            unique_together={('date', 'hour')},
        ),
        migrations.DeleteModel(
            name='HourlySnapshot',
        ),
    ]
