# Generated by Django 5.2.6 on 2025-09-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0003_alter_marketrecord_options_marketrecord_hour_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='granularity',
            field=models.CharField(choices=[('daily', 'Daily'), ('hourly', 'Hourly'), ('30m', '30 Minutes'), ('15m', '15 Minutes'), ('5m', '5 Minutes')], default='daily', max_length=10),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='dii',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='fii',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='global_markets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='pcr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='marketrecord',
            unique_together={('date', 'hour', 'granularity')},
        ),
    ]
