# Generated by Django 5.2.6 on 2025-09-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0004_alter_marketrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketrecord',
            unique_together={('date', 'hour')},
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='dii',
            field=models.DecimalField(decimal_places=2, default=0, help_text='DII activity', max_digits=15),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='fii',
            field=models.DecimalField(decimal_places=2, default=0, help_text='FII activity', max_digits=15),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='global_markets',
            field=models.CharField(blank=True, help_text='e.g. US up, Asia down', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='hour',
            field=models.TimeField(blank=True, help_text='Null = daily, set = hourly snapshot', null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='pcr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Put/Call Ratio', max_digits=5),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='points',
            field=models.IntegerField(default=0, help_text='e.g. +100 or -100'),
        ),
        migrations.RemoveField(
            model_name='marketrecord',
            name='granularity',
        ),
    ]
