# Generated by Django 5.2.6 on 2025-09-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0005_alter_marketrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketrecord',
            name='important_news',
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='dii',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='fii',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='global_markets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='pcr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=100)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('market_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='marketdata.marketrecord')),
            ],
        ),
    ]
