# Generated by Django 5.2.6 on 2025-09-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0007_marketrecord_important_news_alter_marketrecord_dii_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('link', models.URLField()),
                ('published_dt', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], max_length=10)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
