# Generated by Django 5.2.6 on 2025-09-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0008_marketnews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketnews',
            options={'ordering': ['-published_dt']},
        ),
        migrations.RemoveField(
            model_name='marketnews',
            name='link',
        ),
        migrations.AddField(
            model_name='marketnews',
            name='content_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketnews',
            name='content_kn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketnews',
            name='content_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketnews',
            name='content_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketnews',
            name='content_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketnews',
            name='title_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketnews',
            name='title_kn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketnews',
            name='title_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketnews',
            name='title_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketnews',
            name='title_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketnews',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketnews',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
