# Generated by Django 5.2.6 on 2025-09-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0009_alter_marketnews_options_remove_marketnews_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketnews',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
