# Generated by Django 5.2.6 on 2025-09-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0010_marketnews_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketnews',
            options={},
        ),
        migrations.RemoveField(
            model_name='marketnews',
            name='fetched_at',
        ),
        migrations.AddField(
            model_name='marketnews',
            name='impact_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='marketnews',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketnews',
            name='sentiment',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], default='Neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='marketnews',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='marketnews',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
