# Generated by Django 5.2.6 on 2025-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0011_alter_marketnews_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiiDiiRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('fii_buy', models.FloatField()),
                ('fii_sell', models.FloatField()),
                ('fii_net', models.FloatField()),
                ('dii_buy', models.FloatField()),
                ('dii_sell', models.FloatField()),
                ('dii_net', models.FloatField()),
            ],
        ),
    ]
