# Generated by Django 5.2.6 on 2025-09-13 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0012_fiidiirecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiidiirecord',
            name='market',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fii_dii', to='marketdata.marketrecord'),
        ),
    ]
