# Generated by Django 5.2.6 on 2025-09-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0013_fiidiirecord_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiidiirecord',
            name='market',
        ),
        migrations.AddField(
            model_name='fiidiirecord',
            name='impact',
            field=models.CharField(choices=[('Bullish', 'Bullish 📈'), ('Bearish', 'Bearish 📉'), ('Neutral', 'Neutral ➖')], default='Neutral', max_length=10),
        ),
    ]
