# Generated by Django 5.2.6 on 2025-09-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0014_remove_fiidiirecord_market_fiidiirecord_impact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiidiirecord',
            name='impact',
        ),
        migrations.AddField(
            model_name='fiidiirecord',
            name='matched',
            field=models.BooleanField(default=False, help_text='MarketRecord decision matches impact or not'),
        ),
        migrations.AddField(
            model_name='fiidiirecord',
            name='suggestion_text',
            field=models.TextField(blank=True, help_text='Trading suggestion', null=True),
        ),
        migrations.AddField(
            model_name='fiidiirecord',
            name='total_z',
            field=models.FloatField(default=0.0, help_text='Normalized score of fii+dii net'),
        ),
    ]
