# Generated by Django 5.2.6 on 2025-09-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0015_remove_fiidiirecord_impact_fiidiirecord_matched_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trap_detected', models.BooleanField(default=False)),
                ('trap_type', models.CharField(blank=True, max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('fii_dii_signal', models.CharField(blank=True, max_length=50)),
                ('future_decision', models.CharField(blank=True, max_length=50)),
                ('stop_loss_support', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stop_loss_resistance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
