# Generated by Django 5.2.6 on 2025-09-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0016_markettrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='markettrap',
            name='related_news',
            field=models.TextField(blank=True, null=True),
        ),
    ]
