# Generated by Django 5.2.6 on 2025-09-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0017_markettrap_related_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('strike_price', models.IntegerField()),
                ('contract_type', models.CharField(max_length=4)),
                ('contract_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('open_interest', models.BigIntegerField(blank=True, null=True)),
                ('change_oi', models.FloatField(blank=True, null=True)),
                ('implied_vol', models.FloatField(blank=True, null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('theta', models.FloatField(blank=True, null=True)),
                ('gamma', models.FloatField(blank=True, null=True)),
                ('vega', models.FloatField(blank=True, null=True)),
                ('oi_change_pct', models.FloatField(blank=True, null=True)),
                ('iv_change_pct', models.FloatField(blank=True, null=True)),
                ('oi_ema_short', models.FloatField(blank=True, null=True)),
                ('oi_ema_long', models.FloatField(blank=True, null=True)),
                ('is_atm', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'strike_price', 'contract_type'], name='marketdata__timesta_834f8d_idx')],
            },
        ),
    ]
