# Generated by Django 5.2.6 on 2025-09-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0018_optionsnapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionsnapshot',
            old_name='change_oi',
            new_name='change_in_oi',
        ),
        migrations.RemoveField(
            model_name='optionsnapshot',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='optionsnapshot',
            name='oi_ema_long',
        ),
        migrations.RemoveField(
            model_name='optionsnapshot',
            name='oi_ema_short',
        ),
        migrations.AddField(
            model_name='optionsnapshot',
            name='identifier',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='optionsnapshot',
            name='contract_type',
            field=models.CharField(max_length=2),
        ),
    ]
