# Generated by Django 5.2.6 on 2025-09-14 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0019_rename_change_oi_optionsnapshot_change_in_oi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptionSnapshot',
        ),
    ]
