# Generated by Django 5.2.6 on 2025-09-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0020_delete_optionsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('call_ltp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('call_oi', models.IntegerField(blank=True, null=True)),
                ('call_iv', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('put_ltp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('put_oi', models.IntegerField(blank=True, null=True)),
                ('put_iv', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('instrument_type', models.CharField(choices=[('OPTION', 'Option'), ('EQUITY', 'Equity')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='marketrecord',
            name='dii',
        ),
        migrations.RemoveField(
            model_name='marketrecord',
            name='fii',
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='dii_buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='dii_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='dii_sell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='fii_buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='fii_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='fii_sell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
