# Generated by Django 5.2.6 on 2025-09-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0021_optionchain_order_remove_marketrecord_dii_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='interval',
            field=models.CharField(choices=[('1d', 'Daily'), ('1h', 'Hourly'), ('30m', '30-Minute')], default='1d', max_length=10),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='global_markets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='hour',
            field=models.TimeField(blank=True, help_text='Null = daily, set = intraday snapshot (hourly or 30m)', null=True),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='pcr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='marketrecord',
            unique_together={('date', 'hour', 'interval')},
        ),
    ]
