# Generated by Django 5.2.6 on 2025-09-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0022_alter_marketrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketrecord',
            name='global_markets',
        ),
        migrations.RemoveField(
            model_name='marketrecord',
            name='important_news',
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='decision',
            field=models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish'), ('Neutral', 'Neutral')], default='Neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
