# Generated by Django 5.2.6 on 2025-09-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0023_remove_marketrecord_global_markets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField(blank=True, null=True)),
                ('interval', models.CharField(choices=[('1d', 'Daily'), ('1h', 'Hourly'), ('30m', '30-Minute')], max_length=10)),
                ('recommendation', models.CharField(choices=[('Call', 'Call'), ('Put', 'Put'), ('Neutral', 'Neutral')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lots', models.CharField(default='Min 1 Lot / Max 5 Lots', max_length=50)),
                ('result', models.CharField(choices=[('Profit', 'Profit'), ('Loss', 'Loss'), ('Pending', 'Pending')], default='Pending', max_length=10)),
            ],
            options={
                'ordering': ['-date', 'hour'],
            },
        ),
    ]
