# Generated by Django 5.2.6 on 2025-09-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0027_alter_prediction_strike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketnews',
            options={'ordering': ['-published_dt']},
        ),
        migrations.AddField(
            model_name='marketnews',
            name='sectors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='marketnews',
            index=models.Index(fields=['published_dt'], name='marketdata__publish_a9775e_idx'),
        ),
        migrations.AddIndex(
            model_name='marketnews',
            index=models.Index(fields=['sentiment'], name='marketdata__sentime_0f9934_idx'),
        ),
        migrations.AddIndex(
            model_name='marketnews',
            index=models.Index(fields=['impact_score'], name='marketdata__impact__8a95f9_idx'),
        ),
    ]
