# Generated by Django 5.2.6 on 2025-09-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0028_alter_marketnews_options_marketnews_sectors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketrecord',
            name='summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='summary_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='summary_kn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='summary_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='summary_te',
            field=models.TextField(blank=True, null=True),
        ),
    ]
