# Generated by Django 5.2.6 on 2025-09-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0029_marketrecord_summary_en_marketrecord_summary_hi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=50, unique=True)),
                ('lookback_days', models.IntegerField(default=30)),
                ('win_rate', models.FloatField(default=0.0)),
                ('avg_pnl', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntradaySlotStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.TimeField()),
                ('lookback_days', models.IntegerField(default=30)),
                ('win_rate', models.FloatField(default=0.0)),
                ('avg_pts', models.FloatField(default=0.0)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('slot_time', 'lookback_days')},
            },
        ),
    ]
