# Generated by Django 5.2.6 on 2025-09-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0030_strategystats_intradayslotstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketrecord',
            name='global_markets',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='important_news',
            field=models.TextField(blank=True, default=''),
        ),
    ]
