# Generated by Django 5.2.6 on 2025-09-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0031_marketrecord_global_markets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketrecord',
            name='interval',
            field=models.CharField(choices=[('1d', 'Daily'), ('1h', 'Hourly'), ('30m', '30-Minute'), ('5m', '5-Minute'), ('3m', '3-Minute')], default='1d', max_length=10),
        ),
    ]
