# Generated by Django 5.2.6 on 2025-09-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0033_alter_marketrecord_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketrecord',
            name='summary_hi',
        ),
        migrations.RemoveField(
            model_name='marketrecord',
            name='summary_kn',
        ),
        migrations.RemoveField(
            model_name='marketrecord',
            name='summary_ta',
        ),
        migrations.RemoveField(
            model_name='marketrecord',
            name='summary_te',
        ),
        migrations.AlterField(
            model_name='marketrecord',
            name='interval',
            field=models.CharField(max_length=10),
        ),
    ]
