# Generated by Django 5.2.6 on 2025-09-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0034_remove_marketrecord_summary_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketrecord',
            name='summary_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='summary_kn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='summary_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='summary_te',
            field=models.TextField(blank=True, null=True),
        ),
    ]
