# Generated by Django 5.2.6 on 2025-09-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0035_marketrecord_summary_hi_marketrecord_summary_kn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direction', models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pcr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fii_signal', models.CharField(blank=True, max_length=20, null=True)),
                ('dii_signal', models.CharField(blank=True, max_length=20, null=True)),
                ('option_sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('signals', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Hit Target', 'Hit Target'), ('Stop Loss', 'Stop Loss'), ('Missed', 'Missed')], default='Pending', max_length=20)),
            ],
        ),
    ]
