# Generated by Django 5.2.6 on 2025-09-29 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0036_tradeplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeplan',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='dii_signal',
            field=models.CharField(default='Neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='fii_signal',
            field=models.CharField(default='Neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='option_sentiment',
            field=models.CharField(default='Neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='pcr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Hit Target', 'Hit Target'), ('Stop Loss', 'Stop Loss')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TradePlanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike', models.IntegerField()),
                ('type', models.CharField(choices=[('CE', 'CE'), ('PE', 'PE')], max_length=2)),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Hit Target', 'Hit Target'), ('Stop Loss', 'Stop Loss')], default='In Progress', max_length=20)),
                ('trade_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='marketdata.tradeplan')),
            ],
        ),
    ]
