# Generated by Django 5.2.6 on 2025-09-29 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0037_alter_tradeplan_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeplan',
            name='pcr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='signals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='OptionTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike', models.IntegerField()),
                ('type', models.CharField(choices=[('CALL', 'CALL'), ('PUT', 'PUT')], max_length=10)),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Hit Target', 'Hit Target'), ('Stop Loss', 'Stop Loss')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='marketdata.tradeplan')),
            ],
        ),
        migrations.DeleteModel(
            name='TradePlanOption',
        ),
    ]
