# Generated by Django 5.2.6 on 2025-09-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0038_alter_tradeplan_pcr_alter_tradeplan_signals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontrade',
            name='ltp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='optiontrade',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='optiontrade',
            name='stop_loss',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='optiontrade',
            name='target',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='optiontrade',
            name='type',
            field=models.CharField(choices=[('CALL', 'CALL'), ('PUT', 'PUT')], max_length=4),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='dii_signal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='entry_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='fii_signal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='option_sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='pcr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='signals',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='stop_loss',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tradeplan',
            name='target',
            field=models.FloatField(),
        ),
    ]
