# Generated by Django 5.2.6 on 2025-09-29 13:14

import marketdata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0039_alter_optiontrade_ltp_alter_optiontrade_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeplan',
            name='expiry',
            field=models.DateField(default=marketdata.models.get_next_expiry),
        ),
    ]
