# Generated by Django 5.2.6 on 2025-10-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0040_tradeplan_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SniperLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('close_price', models.FloatField()),
                ('atm', models.IntegerField()),
                ('ce_100', models.FloatField()),
                ('pe_100', models.FloatField()),
                ('sniper', models.FloatField()),
                ('upper', models.FloatField()),
                ('lower', models.FloatField()),
                ('upper_double', models.FloatField()),
                ('lower_double', models.FloatField()),
                ('bias', models.CharField(default='Neutral', max_length=20)),
                ('safe_side', models.CharField(default='CE', max_length=5)),
                ('safe_strike', models.IntegerField(blank=True, null=True)),
                ('confidence', models.IntegerField(default=50)),
                ('trade_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
