# Generated by Django 5.2.6 on 2025-10-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0041_sniperlevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sniperlevel',
            options={},
        ),
        migrations.AddField(
            model_name='sniperlevel',
            name='entry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sniperlevel',
            name='risk_reward',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sniperlevel',
            name='stoploss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sniperlevel',
            name='target1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sniperlevel',
            name='target2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sniperlevel',
            name='safe_side',
            field=models.CharField(default='CE', max_length=10),
        ),
    ]
