# Generated by Django 5.2.6 on 2025-10-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0042_alter_sniperlevel_options_sniperlevel_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sniperlevel',
            name='bias',
        ),
        migrations.RemoveField(
            model_name='sniperlevel',
            name='ce_100',
        ),
        migrations.RemoveField(
            model_name='sniperlevel',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='sniperlevel',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='sniperlevel',
            name='pe_100',
        ),
        migrations.RemoveField(
            model_name='sniperlevel',
            name='risk_reward',
        ),
        migrations.RemoveField(
            model_name='sniperlevel',
            name='safe_side',
        ),
        migrations.RemoveField(
            model_name='sniperlevel',
            name='safe_strike',
        ),
        migrations.RemoveField(
            model_name='sniperlevel',
            name='stoploss',
        ),
        migrations.RemoveField(
            model_name='sniperlevel',
            name='target1',
        ),
        migrations.RemoveField(
            model_name='sniperlevel',
            name='target2',
        ),
        migrations.RemoveField(
            model_name='sniperlevel',
            name='trade_note',
        ),
        migrations.CreateModel(
            name='SniperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=5)),
                ('strike', models.IntegerField()),
                ('entry', models.FloatField()),
                ('stoploss', models.FloatField()),
                ('target1', models.FloatField()),
                ('target2', models.FloatField()),
                ('risk_reward', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence', models.IntegerField(default=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('sniper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='marketdata.sniperlevel')),
            ],
        ),
    ]
