# Generated by Django 5.2.6 on 2025-10-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0043_remove_sniperlevel_bias_remove_sniperlevel_ce_100_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sniperlevel',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='snipertrade',
            options={'ordering': ['-sniper__date', 'strike', 'side']},
        ),
        migrations.AddField(
            model_name='snipertrade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sniperlevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='snipertrade',
            name='risk_reward',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='snipertrade',
            name='side',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='snipertrade',
            name='target2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
