# Generated by Django 5.2.6 on 2025-10-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0044_alter_sniperlevel_options_alter_snipertrade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snipertrade',
            name='action',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
