# Generated by Django 5.2.6 on 2025-10-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0045_snipertrade_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='sniperlevel',
            name='bias',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
