# Generated by Django 5.2.6 on 2025-10-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0046_sniperlevel_bias'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('atm', models.FloatField()),
                ('upper', models.FloatField()),
                ('lower', models.FloatField()),
                ('sniper', models.FloatField()),
                ('bias', models.CharField(max_length=20)),
                ('routine_before', models.TextField()),
                ('routine_during', models.TextField()),
                ('routine_rules', models.TextField()),
                ('routine_extra', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('date', models.DateField()),
                ('interval_minutes', models.IntegerField(default=20)),
                ('close', models.FloatField(blank=True, null=True)),
                ('atm', models.IntegerField(blank=True, null=True)),
                ('sniper', models.FloatField(blank=True, null=True)),
                ('total_call_profit', models.FloatField(blank=True, null=True)),
                ('total_put_profit', models.FloatField(blank=True, null=True)),
                ('call_volume', models.BigIntegerField(blank=True, null=True)),
                ('put_volume', models.BigIntegerField(blank=True, null=True)),
                ('call_oi', models.BigIntegerField(blank=True, null=True)),
                ('put_oi', models.BigIntegerField(blank=True, null=True)),
                ('trap_flag', models.BooleanField(default=False)),
                ('trap_note', models.TextField(blank=True, null=True)),
                ('recommendation', models.CharField(default='Monitor', max_length=20)),
                ('raw_chain', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MarketSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=2)),
                ('strike', models.IntegerField()),
                ('ltp', models.FloatField()),
                ('oi', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('est_profit', models.FloatField(blank=True, null=True)),
                ('trap', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='marketdata.marketsnapshot')),
            ],
            options={
                'ordering': ['-snapshot__timestamp', 'side', 'strike'],
            },
        ),
    ]
