# Generated by Django 5.2.6 on 2025-10-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0047_dailyplan_marketsnapshot_marketsignal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyPlan',
        ),
        migrations.AlterUniqueTogether(
            name='marketrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marketrecord',
            name='index',
            field=models.CharField(choices=[('NIFTY', 'Nifty 50'), ('SENSEX', 'Sensex 30'), ('BANKNIFTY', 'Bank Nifty')], default='NIFTY', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='marketrecord',
            unique_together={('index', 'date', 'hour', 'interval')},
        ),
    ]
