# Generated by Django 5.2.6 on 2025-10-05 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0048_delete_dailyplan_alter_marketrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketrecord',
            old_name='close',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='marketrecord',
            old_name='high',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='marketrecord',
            old_name='nifty_low',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='marketrecord',
            old_name='open',
            new_name='open',
        ),
    ]
