# Generated by Django 5.2.6 on 2025-10-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(choices=[('NIFTY', 'Nifty 50'), ('SENSEX', 'Sensex 30'), ('BANKNIFTY', 'Bank Nifty')], max_length=10)),
                ('interval', models.CharField(default='1d', max_length=10)),
                ('reversal_date', models.DateField()),
                ('from_trend', models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish')], max_length=10)),
                ('to_trend', models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish')], max_length=10)),
                ('prev_streak_days', models.IntegerField(default=0)),
                ('new_streak_days', models.IntegerField(default=0)),
                ('prev_change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('momentum_bias', models.CharField(choices=[('BUY_CE', 'Call Bias (Buy CE)'), ('BUY_PE', 'Put Bias (Buy PE)'), ('NEUTRAL', 'Neutral / Avoid')], default='NEUTRAL', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-reversal_date'],
                'unique_together': {('index', 'interval', 'reversal_date', 'from_trend', 'to_trend')},
            },
        ),
    ]
