# Generated by Django 5.2.6 on 2025-10-04 14:38

import django.db.models.deletion
import tradeapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(choices=[('NIFTY', 'Nifty 50'), ('BANKNIFTY', 'Bank Nifty'), ('SENSEX', 'Sensex 30')], default='NIFTY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.FloatField()),
                ('direction', models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], max_length=10)),
                ('entry_price', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('target', models.FloatField()),
                ('confidence', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('pcr', models.FloatField(blank=True, null=True)),
                ('fii_signal', models.CharField(blank=True, max_length=20, null=True)),
                ('dii_signal', models.CharField(blank=True, max_length=20, null=True)),
                ('option_sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('signals', models.JSONField(default=dict)),
                ('expiry', models.DateField(default=tradeapp.models.get_next_expiry)),
            ],
        ),
        migrations.CreateModel(
            name='OptionTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike', models.IntegerField()),
                ('type', models.CharField(choices=[('CALL', 'CALL'), ('PUT', 'PUT')], max_length=4)),
                ('ltp', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('target', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tradeapp.tradeplan')),
            ],
        ),
    ]
